# Generated by Django 5.0.6 on 2024-05-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer_order_orderproduct_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='weight',
        ),
    ]
