# Generated by Django 5.0.6 on 2024-05-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_quantity_product_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='quantity',
        ),
    ]
